### PR TITLE
Create CHAT.TXT

### PR DESCRIPTION
**Pull request by macguyversmusic**
README COSMIC-SNOW :-)

## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] I have added thorough documentation for my code.
- [ ] I have tagged PR with relevant project labels. I acknowledge that a PR without labels may be dismissed.
- [ ] If this PR addresses a bug, I have provided both a screenshot/video of the original bug and the working solution.

### CODE REVIEW

**Comment by cosmic-snow** [comment]
@macguyversmusic Oh hey, sorry. I didn't actually expect anyone to open a pull request here. And it didn't even show up in my notifications. (Probably better to try with @...)

Well, so far my interest is amateur. The last time I did anything ML related was years ago. But now that it has picked up a lot of steam I decided I'd go and help out with *something*.

My main interest here is with prompting, trying to make those things more useful. But that has kind of taken a backseat recently. I hope to get back to it once things have calmed down a bit.

Anyway, regarding your problem:
- I open `gpt4all-chat\CMakeLists.txt` in Qt Creator
- (I've cloned the repository a few times for different things now and always forget the submodules. Reminder: `git submodule update --init` or related commands)
- Projects > Build Settings > Initial Configuration: Override `CMAKE_GENERATOR` with `Visual Studio 17 2022`
  - you might want to do this for both the Debug and Release configuration
- run cmake

It should produce Visual Studio projects and a solution file in a subfolder of the project directory. You can use these in Visual Studio directly. But don't try to let VS run cmake -- or if you do, I'd be interested to know how you got it to work. 😉

Both Qt Creator and VS should at this point be able to build. Although I mostly stay in Qt Creator at the moment. If you get build errors: first try to build again. Although note: the setting that causes them was "fixed" in the most recent commit. So just pull first.

If you still get build errors, I'd probably need to see them.


Sorry, I've never made a Reddit account, although I do spend time reading in some subreddits on occasion.


Oh yes, my name is Dominik. Nice to meet you.

**Comment by macguyversmusic** [comment]
image

and thank you!

@cosmic-snow i managed to build the exe for sure and its missing all sorts of dlls but im sure i can get past that.  i will start again also.  one thing i note is when i put the v studio 17 2022 or whatever it is in the CMAKE_GENERATOR  it remains red...   but i not replacing with ninja afterwards also stays red so im not sure.  anyway this is progress as far as im concerned and i saw the little localhost flag in the build settings i never saw before

i will delete this pull request and fork now. i never knew about @cosmic-snow calling here.  thanks for the input

**Comment by cosmic-snow** [comment]
Great, you got it to work.

Ah you can keep it open and we can chat here if you want, I don't mind.

So what other DLLs are you missing now? Have you installed the Windows 10 SDK with the VS installer?

Yes, it's red. I don't know why, probably to make it clear it's a user setting. By the way, they managed to activate CI/CD on the repository and it includes an automated Windows build. So that's basically a template to get everything to work, too. Curiously, it's using ninja, but I haven't tried switching to that myself.

**Comment by cosmic-snow** [comment]
@macguyversmusic sorry, I actually forgot to ping you again when I responded. 🙄

Did you get everything to work?

**Comment by macguyversmusic** [comment]
not yet brother.  still struggling.  i can actually debug or run it from qt
with no vstudio involvement but it only seems to compile the exe and then
other times a bunch of other dll files.
i was kind of hoping there will be another update along the way and some of
this will become simpler.

**Comment by cosmic-snow** [comment]
@macguyversmusic 
I think it might also do some deployment step in Qt before it runs it that might be missing in Visual Studio. If I do a successful build & run in Qt, but then go into the project folder with the .exe, I can't simply run it from there.

Also note, if you've pulled from the main branch recently, there is currently a bug with MSVC. I've made a pull request for a fix some time ago, but it didn't get merged yet.

I haven't yet looked into building the whole project with Visual Studio again. But I did install the VS Qt extension in the meantime, so maybe that will help when I try that next time.

**Comment by macguyversmusic** [comment]
i think maybe a clean environment would be the way but man i spent
soooooooo many hours trying to compile it and i end up realizing for what i
want to do i could have coded the app myself by now and so i am off
investigating other methods to work with the ggml models and i think ill
just make THE simple wrapper.  a dropdown to select compatible models in
the MODELS subfolder of the project and a basic single window to talk with
the model to start.
things just move so fast i dont think i can justifiably try even though it
annoys me sufficiently that i want to get the best of it, its a side track
to getting a compileable app that serves my purpose.

have you trained much? i started more in the diffusion models and did a lot
of work with clients implementing all sorts of things, it amazes me how
essentially we are just using words all of these different generative
techs, just vector math and words broken in to tokens!

anyway thanks for the help, i will be sure to look at the page again if i
get the chance or time to make a clean environment.  i was thinking to do
it on a windows 10 virtual box image, then clone the damn thing but doesnt
it seem crazy that you would clone an install and freexe it in order to be
able to compile a certain program? ha

have a great sunday!

Stuart

**Comment by macguyversmusic** [comment]
i didnt realise replying to these emails posted to github!  feel free to
remove whatever is not on topic

**Comment by cosmic-snow** [comment]
@macguyversmusic 
> i didnt realise replying to these emails posted to github!  feel free to
remove whatever is not on topic

oh that's fine. this repo's only purpose is pull requests anyway.

> i think maybe a clean environment would be the way but man i spent
soooooooo many hours trying to compile it and i end up realizing for what i
want to do i could have coded the app myself by now and so i am off
investigating other methods to work with the ggml models and i think ill
just make THE simple wrapper.  a dropdown to select compatible models in
the MODELS subfolder of the project and a basic single window to talk with
the model to start.

yes, i've spent quite some time on annoying problems, too. i guess it was just a bad time to start. the backend change that allows several formats at once created a number of issues, although now many have finally been fixed (the MSVC pull request I made is in, too). i've stumbled on that web UI you mentioned before, but haven't tried it yet myself. 

> things just move so fast i dont think i can justifiably try even though it
annoys me sufficiently that i want to get the best of it, its a side track
to getting a compileable app that serves my purpose.

if you want something simple, maybe just create it with the bindings? those for Python got another fix today; still not perfect but most models work again. I think Go got a fix, but I don't use that. C# doesn't work, but soon I guess. Java & Typescript probably soon, too.

> have you trained much? i started more in the diffusion models and did a lot
of work with clients implementing all sorts of things, it amazes me how
essentially we are just using words all of these different generative
techs, just vector math and words broken in to tokens!

have not yet looked into training models. but yes, i've started learning about the building blocks, it's really quite interesting. although i'm still pretty busy "catching up" so to speak. or at least i'm trying to.

> anyway thanks for the help, i will be sure to look at the page again if i
get the chance or time to make a clean environment.  i was thinking to do
it on a windows 10 virtual box image, then clone the damn thing but doesnt
it seem crazy that you would clone an install and freexe it in order to be
able to compile a certain program? ha

heh, not really. see all the container stuff. i've also made some Linux VMs i can just reset back to the initial state. helps a lot when troubleshooting, to make sure nothing i did earlier is interfering.

> have a great sunday!

thanks, hope you had a good one, too.

**Pull request closed without merging**
